/** Generated by the default template from graphql-java-generator */
package org.forum.server.jpa;

import java.util.List;
import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Transient;

@Entity(name = "Board")
public class BoardEntity {

	@Id
	@GeneratedValue
	UUID id;

	String name;

	boolean publiclyAvailable;

	@Transient
	List<TopicEntity> topics;

	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isPubliclyAvailable() {
		return publiclyAvailable;
	}

	public void setPubliclyAvailable(boolean publiclyAvailable) {
		this.publiclyAvailable = publiclyAvailable;
	}

	public List<TopicEntity> getTopics() {
		return topics;
	}

	public void setTopics(List<TopicEntity> topics) {
		this.topics = topics;
	}

}
